a= eval(input("Enter a list"))
b= sum(a)
c= b/(len(a))
max= max(a)
min= min(a)
sort= sorted(a)
print("Summation : ", b)
print("Average number : ",c)
print("Maximum value : "  ,max)
print("Minimum number :",min)
print("Sorted number",sort)